# Generated by Django 5.1.2 on 2024-10-16 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('delivery_manager', 'Delivery Manager'), ('internal_manager', 'Internal Manager')], default='delivery_manager', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('delivery_manager', 'Delivery Manager'), ('internal_manager', 'Internal Manager')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserJobType',
        ),
        migrations.RemoveField(
            model_name='users',
            name='affiliation_type',
        ),
        migrations.RemoveField(
            model_name='wholesaler',
            name='area',
        ),
        migrations.AddField(
            model_name='users',
            name='affiliation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='affiliation_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='job_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='job_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close'), ('rest', 'Rest'), ('closed_days', 'Closed Days')], default='closed', max_length=50),
        ),
        migrations.AddField(
            model_name='affiliationmembers',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_requests', to='management.wholesaler'),
        ),
        migrations.AddField(
            model_name='affiliationmembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='management.country'),
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='management.city'),
        ),
        migrations.AddField(
            model_name='affiliationmembers',
            name='assigned_areas',
            field=models.ManyToManyField(blank=True, related_name='assigned_members', to='management.district'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_districts', to='management.district'),
        ),
        migrations.AddField(
            model_name='wholesaler',
            name='service_areas',
            field=models.ManyToManyField(blank=True, related_name='wholesalers', to='management.district'),
        ),
        migrations.AddField(
            model_name='manager',
            name='assigned_areas',
            field=models.ManyToManyField(blank=True, related_name='managers', to='management.district'),
        ),
        migrations.AddField(
            model_name='manager',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='management.wholesaler'),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='districts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood', to='management.city'),
        ),
    ]
