# Generated by Django 5.1.1 on 2024-10-05 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(max_length=50)),
                ('sync_status', models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure')], max_length=50)),
                ('sync_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.JSONField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(max_length=13, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserJobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(choices=[('wholesaler', 'Wholesaler'), ('buyer', 'Buyer'), ('customer', 'Customer'), ('manager', 'Manager')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=13, null=True)),
                ('gtin', models.CharField(blank=True, max_length=14, null=True)),
                ('gpc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('food_industry_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.totalproducts')),
            ],
            options={
                'unique_together': {('barcode', 'gtin', 'gpc_code', 'food_industry_code')},
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.BinaryField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('affiliation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('affiliation_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.userjobtype')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('kakao_id', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.users')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('kakao_id', models.CharField(blank=True, max_length=100, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('business_registration_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('business_registration_certificate', models.BinaryField(blank=True, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_products', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close'), ('rest', 'Rest'), ('closed_days', 'Closed Days')], default='open', max_length=50)),
                ('approve_status', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('hold', 'Hold')], default='hold', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.users')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_status', models.CharField(choices=[('Valid', 'Valid'), ('Invalid', 'Invalid')], max_length=50)),
                ('validation_message', models.TextField()),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.productcodes')),
            ],
        ),
        migrations.CreateModel(
            name='Wholesalers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_info', models.JSONField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close'), ('rest', 'Rest'), ('closed_days', 'Closed Days')], default='open', max_length=50)),
                ('approve_status', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('hold', 'Hold')], default='hold', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.users')),
            ],
        ),
        migrations.CreateModel(
            name='Quotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('details', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('selected', 'Selected'), ('purchase_request', 'Purchase Request'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='received', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.buyer')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.customer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.wholesalers')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_data', models.JSONField()),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('updated', 'Updated')], default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.totalproducts')),
                ('wholesaler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.wholesalers')),
            ],
            options={
                'unique_together': {('total_product', 'wholesaler')},
            },
        ),
        migrations.CreateModel(
            name='SaleProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_status', models.CharField(choices=[('new', 'New'), ('updated', 'Updated')], default='new', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.products')),
                ('wholesaler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.wholesalers')),
            ],
            options={
                'unique_together': {('wholesaler', 'product')},
            },
        ),
    ]
